[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.33",
    "plotly>=6.1.2",
    "streamlit-autorefresh>=1.0.1",
    "streamlit>=1.45.1",
    "botocore>=1.38.33",
    "pandas>=2.3.0",
    "reportlab>=4.4.1",
    "openai>=1.85.0",
    "anthropic>=0.53.0",
    "trafilatura>=2.0.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "numpy>=2.3.0",
    "geoip2>=5.1.0",
]
